### PR TITLE
document default with Symbol in type

### PR DESCRIPTION
**Pull request by BebeSparkelSparkel**
This puts the default value as a Symbol in the Opt type.

### CODE REVIEW

**Comment by BebeSparkelSparkel** [comment]
#20

**Comment by BebeSparkelSparkel** [comment]
This should not be pulled without scrutiny

**Comment by BebeSparkelSparkel** [comment]
This can now display the default values for options and environment variable while statically checking if unrender works on the default provided string value.

The following test files show how this looks in practice (look for Def in the test name)
test/Options/Commander/OptionSpec.hs
test/Options/Commander/EnvironmentSpec.hs

**Comment by SamuelSchlesinger** [comment]
This change is far too large for me to feel comfortable reviewing and merging in one go. Please break it up into more bite sized changes so I can feel confident that it is correct and desirable. Anyways, I'm grateful for all of the cleanup and refactoring work you've been doing 👍

**Pull request closed without merging**
